### PR TITLE
ESP01 variant clocked at 160MHz

### PR DESCRIPTION
**Pull request by Sermus**
Added preloop() function. It's empty for existing boards
Added generic esp01 working at 160MHz

### CODE REVIEW

**Comment by igrr** [comment]
Can we set the frequency in ```initVariant()```?

**Comment by Sermus** [comment]
Nop, it needs to be set repeatedly, otherwise SDK routines switch it back to 80

**Comment by phenom128** [comment]
set once at init?, (??? for changing after initialisation, poss add a func
setfreq(n) sets freq to n & does anything extra needed ???)
then use value many times, otherwise SDK routines switch it back to 80
.
stephen

**Comment by igrr** [comment]
Yeah, I think adding an API to set frequency would be better than adding a
board variant -- since going from 80 to 160 is only a software change, not
related to the board (which is the case with AVRs, for instance).

Maybe we should add a library for all the chip-related APIs, like
frequency, sleep/ deep sleep, what do you guys think?

**Comment by Sermus** [comment]
What do we do with F_CPU def?

**Comment by Sermus** [comment]
Arduino ecosystem doesn't seem to be ready to freq-variable CPUs since. The F_CPU is an evidence. There is code depending on freq. Again, if we want one-to-one portability we need to stick to freq-constant hardware. This was the driving factor for making another target board.

**Comment by igrr** [comment]
>What do we do with F_CPU def?
```#define F_CPU (1000000 * *((volatile uint32_t*)0x3FFFC704))```

Okay, I think we can have both have a compile-time setting and a run-time one for people who know what they are doing.
Will merge this today, thank you.

**Comment by igrr** [comment]
https://github.com/esp8266/Arduino/commit/3bde54d5844610633f34c636977b7b2b80131e50

I added F_CPU selection via an additional menu, since other board variants may also be used at 160MHz.

**Pull request closed without merging**
